Start screen
Engame-Coding-Society/engame-quiz pull request #28
Opened 2024-01-12 19:05 UTC by yefetk

Bocs a hogy csak most toltom fel de valamiert nem birtam mukodesre birni. Barmit csinaltam mindig valami mas baja volt.

2024-01-12 19:17 UTC, ProgrammerPeter2 requested changes
Please do the following changes and make sure its working. Prove it with a screenshot please.

2024-01-12 19:17 UTC, ProgrammerPeter2 commented on screens/WelcomeScreen.py
> +    def __init__(self, screen_size, clock, loader):
Add set_callback as a constructor param

2024-01-12 19:17 UTC, ProgrammerPeter2 commented on screens/WelcomeScreen.py
> +        self.init_ui()
Add self.set_callback before line 9 and set the set_callback constructor parameter to its value.

2024-01-12 19:26 UTC, yefetk commented
![Uploading Screenshot 2024-01-12 202508.png…]()

2024-01-12 19:29 UTC, yefetk commented
still not working

2024-01-12 19:29 UTC, yefetk commented
![Uploading Screenshot 2024-01-12 202854.png…]()

2024-01-12 19:36 UTC, ProgrammerPeter2 commented
Then push it and we'll figure it out what's wrong

2024-01-12 19:36 UTC, yefetk commented
ok

2024-01-12 20:12 UTC, ProgrammerPeter2 commented
I'll test this out tommorrow morning! I hope it will work until our meeting!

2024-01-13 21:53 UTC, ProgrammerPeter2 approved these changes

2024-02-18 15:37 UTC, merged